version: '3'
services:
  app:
    build: .  # Path to the directory containing the Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    command: /bin/bash -c "uvicorn api.main:app --host 0.0.0.0 --reload & streamlit run frontend/app.py"
